name: Deploy static website to S3 and invalidate CloudFront

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # 이미지 최적화
    - name: Optimize images
      uses: calibreapp/image-actions@main
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        compressOnly: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to S3
      run: |
        aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} \
          --delete \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --exclude "README.md" \
          --cache-control "public, max-age=31536000" \
          --metadata-directive REPLACE \
          --content-type "text/html; charset=utf-8" \
          --include "*.html" \
          --include "*.css" \
          --include "*.js" \
          --include "*.webp" \
          --include "*.jpg" \
          --include "*.png"

    # HTML 파일 캐시 설정
    - name: Set proper Cache-Control for HTML files
      run: |
        aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/ s3://${{ secrets.S3_BUCKET_NAME }}/ \
          --recursive \
          --exclude "*" \
          --include "*.html" \
          --metadata-directive REPLACE \
          --cache-control "no-cache, no-store, must-revalidate" \
          --content-type "text/html; charset=utf-8"

    # 이미지 파일 캐시 설정
    - name: Set proper Cache-Control for Image files
      run: |
        aws s3 sync images/ s3://${{ secrets.S3_BUCKET_NAME }}/images \
          --cache-control "public, max-age=2592000"  # 30일 (2592000초)
    
    # CSS 파일 캐시 설정
    - name: Set proper Cache-Control for CSS files
      run: |
        aws s3 sync css/ s3://${{ secrets.S3_BUCKET_NAME }}/css \
          --exclude "*.html" \
          --cache-control "public, max-age=604800, must-revalidate" \
          --content-type "text/css; charset=utf-8"
    
    # JS 파일 캐시 설정
    - name: Set proper Cache-Control for JS files
      run: |
        aws s3 sync js/ s3://${{ secrets.S3_BUCKET_NAME }}/js \
          --exclude "*.html" \
          --cache-control "public, max-age=604800, must-revalidate"  # 7일 (604800초)
    
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"
