name: Deploy Static Assets to S3 and invalidate CloudFront

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy static files to S3
        run: |
          # 정적 파일 동기화 캐시 설정 (30일)
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "node_modules/*" \
            --cache-control "public, max-age=2592000" \

          # 이미지 파일 캐시 설정 (30일)
          aws s3 sync img/ s3://${{ secrets.S3_BUCKET_NAME }}/img \
            --cache-control "public, max-age=2592000" \

          # CSS/JS 캐시 설정 (7일, 검증 필요)
          aws s3 sync css/ s3://${{ secrets.S3_BUCKET_NAME }}/css \
            --exclude "*.html" \
            --cache-control "public, max-age=604800, must-revalidate" \

          aws s3 sync js/ s3://${{ secrets.S3_BUCKET_NAME }}/js \
            --exclude "*.html" \
            --cache-control "public, max-age=604800, must-revalidate" \

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
